name: StoreScreenshot

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  store-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.3.2
        with:
          gradle-version: wrapper

      - name: record screenshot
        id: record-test
        run: |
          ./gradlew recordRoborazziDebug --stacktrace --rerun-tasks

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot
          path: "**/build/outputs/roborazzi"
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-reports
          path: "**/build/reports"
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-test-results
          path: "**/build/test-results"
          retention-days: 30
